# Generated by Django 6.0.2 on 2026-02-10 23:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('low', 'Low'), ('uneasy', 'Uneasy'), ('okay', 'Okay'), ('bright', 'Bright')], max_length=20)),
                ('stress_level', models.PositiveSmallIntegerField()),
                ('sleep_hours', models.DecimalField(decimal_places=1, max_digits=4)),
                ('weekly_calm', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
